name: Docker Image CI

on:
  push:
    branches: [ "Branch_10.0.2" ]
  pull_request:
    branches: [ "Branch_10.0.2" ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: |
    #     cd server;
    #     docker build . --file Dockerfile --tag liuxincuit/keycloak:10.0.2
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}
          
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
      with:
        context: ./server
        push: ${{ github.event_name != 'pull_request' }}
        tags: liuxincuit/keycloak:10.0.2
